version: "3.7"

services:
  opire_web:
    image: node:20-alpine
    container_name: opire_web
    working_dir: "/app"
    tty: true
    network_mode: host
    volumes:
      - .:/app
    ports:
      - 4321:4321
